//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageBloodTypes.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLichSuGiaoDich
    {
        public int IDGiaoDich { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public Nullable<int> IDNhomMau { get; set; }
        public Nullable<bool> TinhTrangYeuCau { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayYeuCau { get; set; }
        public Nullable<int> SoLuongMau { get; set; }
        public Nullable<System.DateTime> NgayXacNhan { get; set; }
        public Nullable<bool> Hide { get; set; }
    }
}
