//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageBloodTypes.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTieuChuan
    {
        public int IDTieuChuan { get; set; }
        public string Icon { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> Hide { get; set; }
    }
}
